Repository telekom/sparrow, pull requests merged in 2023-12, with the labels that each got.

#25 Ci/action
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/test_sast.yml
  .github/workflows/test_unit.yml
  .goreleaser-ci.yaml
  .goreleaser.yaml
  Dockerfile
  README.md
Labels: enhancement

#26 [Feature] Helm chart
  .github/workflows/ci.yml
  .github/workflows/end2end.yml
  .github/workflows/release.yml
  .goreleaser-ci.yaml
  .pre-commit-config.yaml
  CODEOWNERS
  NOTICE
  README.md
  chart/Chart.yaml
  chart/README.md
  chart/templates/_helpers.tpl
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/ingress.yaml
  chart/templates/networkpolicy.yaml
  chart/templates/secret.yaml
  chart/templates/service.yaml
  chart/templates/serviceaccount.yaml
  chart/values.yaml
  docs/img/sparrow.png
Labels: enhancement

#24 chore/linting
  .golangci.yaml
  .pre-commit-config.yaml
  cmd/gen-docs.go
  cmd/run.go
  docs/sparrow.md
  docs/sparrow_completion.md
  docs/sparrow_completion_bash.md
  docs/sparrow_completion_fish.md
  docs/sparrow_completion_powershell.md
  docs/sparrow_completion_zsh.md
  docs/sparrow_gen-docs.md
  docs/sparrow_run.md
  internal/helper/retry.go
  internal/helper/retry_test.go
  internal/logger/logger.go
  pkg/api/routingtree.go
  pkg/api/routingtree_test.go
  pkg/checks/health.go
  pkg/checks/health_test.go
  pkg/checks/latency.go
  pkg/checks/latency_test.go
  pkg/checks/oapi_test.go
  pkg/config/http.go
  pkg/config/loader.go
  pkg/config/validate.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/sparrow/api.go
  pkg/sparrow/api_test.go
  pkg/sparrow/run.go
Labels: refactoring, housekeeping

#38 chore: adjust feature request template to new labels
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: housekeeping

#29 fix: latency test race condition
  .pre-commit-config.yaml
  .vscode/settings.json
  docs/sparrow.md
  docs/sparrow_completion.md
  docs/sparrow_completion_bash.md
  docs/sparrow_completion_fish.md
  docs/sparrow_completion_powershell.md
  docs/sparrow_completion_zsh.md
  docs/sparrow_gen-docs.md
  docs/sparrow_run.md
  go.mod
  go.sum
  pkg/checks/checks.go
  pkg/checks/health.go
  pkg/checks/latency.go
  pkg/checks/latency_test.go
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
Labels: bug, refactoring, housekeeping

#39 docs: rm auto gen tag
  cmd/gen-docs.go
  docs/sparrow.md
  docs/sparrow_completion.md
  docs/sparrow_completion_bash.md
  docs/sparrow_completion_fish.md
  docs/sparrow_completion_powershell.md
  docs/sparrow_completion_zsh.md
  docs/sparrow_gen-docs.md
  docs/sparrow_run.md
Labels: docs, housekeeping

#40 fix: latency req timeout calc
  .gitignore
  pkg/checks/latency.go
  pkg/checks/latency_test.go
  pkg/sparrow/api.go
Labels: bug

#41 Refactor: use time.After
  internal/helper/retry.go
  pkg/config/http.go
Labels: refactoring

#42 Fix/health shutdown
  .github/workflows/test_unit.yml
  .gitignore
  pkg/checks/checks_moq.go
  pkg/checks/health.go
  pkg/checks/health_test.go
Labels: bug

#45 feat: add metrics; fix latency check; latency time in sec
  README.md
  go.mod
  go.sum
  pkg/checks/checks.go
  pkg/checks/checks_moq.go
  pkg/checks/health.go
  pkg/checks/health_test.go
  pkg/checks/latency.go
  pkg/checks/latency_test.go
  pkg/sparrow/api.go
  pkg/sparrow/api_test.go
  pkg/sparrow/metrics.go
  pkg/sparrow/metrics_moq.go
  pkg/sparrow/metrics_test.go
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
Labels: feature, request/internal, area/checks

#49 feat: added dns name to sparrow
  README.md
  cmd/run.go
  docs/sparrow_run.md
  pkg/config/config.go
  pkg/config/flags.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/sparrow/run.go
Labels: request/internal

#50 Global target pass-down to the Checks
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
  pkg/sparrow/targets/test/mocktargets.go
Labels: request/internal

#51 feat/target-manager-shutdown
  cmd/run.go
  pkg/sparrow/api.go
  pkg/sparrow/gitlab/gitlab.go
  pkg/sparrow/gitlab/gitlab_test.go
  pkg/sparrow/gitlab/test/mockclient.go
  pkg/sparrow/run.go
  pkg/sparrow/targets/gitlab.go
  pkg/sparrow/targets/gitlab_test.go
Labels: request/internal
