Repository telekom/sparrow, pull requests merged in 2024-01, with the labels that each got.

#54 feat(helm): add target manager support
  README.md
  chart/Chart.yaml
  chart/README.md
  chart/templates/_helpers.tpl
  chart/templates/deployment.yaml
  chart/templates/secret.yaml
  chart/values.yaml
Labels: feature

#57 feat: always activate health endpoint; rm unnecessary config
  README.md
  chart/README.md
  chart/templates/configmap.yaml
  chart/values.yaml
  pkg/checks/health.go
  pkg/checks/health_test.go
Labels: refactoring

#58 Make target manager optional
  .github/workflows/end2end.yml
  chart/README.md
  chart/templates/deployment.yaml
  chart/values.yaml
  cmd/run.go
  docs/sparrow_run.md
  pkg/config/config.go
  pkg/sparrow/run.go
Labels: housekeeping, area/target-manager

#59 feat: add simple okHandler for api
  pkg/sparrow/api.go
  pkg/sparrow/api_test.go
Labels: feature, housekeeping

#62 Refactor: Move doc gen from sparrow binary to its own script
  chart/README.md
  cmd/root.go
  docs/sparrow.md
  docs/sparrow_gen-docs.md
  scripts/gen-docs/gen-docs.go
Labels: housekeeping

#67 fix: only include json files in gtm file list
  pkg/sparrow/gitlab/gitlab.go
  pkg/sparrow/gitlab/gitlab_test.go
Labels: bug

#68 chore: removed dedicated targetManager config
  .gitignore
  .pre-commit-config.yaml
  README.md
  chart/README.md
  chart/templates/deployment.yaml
  chart/templates/secret.yaml
  chart/values.yaml
  cmd/root.go
  cmd/run.go
  docs/sparrow_run.md
  go.mod
  pkg/checks/latency.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/flags.go
  pkg/config/testdata/tmconfig.yaml
Labels: refactoring, area/target-manager

#63 Refactor: Config and CLI
  .github/workflows/end2end.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  chart/README.md
  chart/templates/deployment.yaml
  chart/templates/secret.yaml
  chart/values.yaml
  cmd/flag.go
  cmd/root.go
  cmd/run.go
  docs/sparrow_run.md
  go.mod
  internal/helper/retry.go
  pkg/checks/health.go
  pkg/checks/latency.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/file.go
  pkg/config/file_test.go
  pkg/config/flags.go
  pkg/config/http.go
  pkg/config/http_test.go
  pkg/config/runtime_config.go
  pkg/config/testdata/tmconfig.yaml
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/sparrow/run_test.go
Labels: refactoring

#69 feat: Service Monitor
  chart/README.md
  chart/templates/servicemonitor.yaml
  chart/values.yaml
Labels: feature, area/helm

#64 feat: match up checks & enhance check config
  chart/README.md
  chart/templates/configmap.yaml
  chart/values.yaml
  internal/helper/decode.go
  internal/helper/decode_test.go
  pkg/checks/checks.go
  pkg/checks/health.go
  pkg/checks/health_test.go
  pkg/checks/latency.go
  pkg/checks/latency_test.go
  pkg/config/validate.go
Labels: feature, refactoring

#61 Error handling; don't panic.
  .gitignore
  chart/README.md
  cmd/run.go
  internal/helper/retry_test.go
  internal/logger/logger.go
  pkg/api/routingtree.go
  pkg/checks/health.go
  pkg/checks/latency.go
  pkg/checks/oapi.go
  pkg/config/file.go
  pkg/config/file_test.go
  pkg/config/http.go
  pkg/config/loader.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/db/db.go
  pkg/sparrow/api.go
  pkg/sparrow/api_test.go
  pkg/sparrow/metrics.go
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
  pkg/sparrow/targets/gitlab.go
  pkg/sparrow/targets/gitlab_test.go
  pkg/sparrow/targets/targetmanager.go
  pkg/sparrow/targets/test/mocktargets.go
  scripts/gen-docs/gen-docs.go
Labels: feature, refactoring

#74 feat: package helm chart on push
  .github/workflows/ci.yml
Labels: feature, area/helm

#73 feat: Prepare helm chart for 0.3.0
  .github/workflows/end2end.yml
  chart/Chart.yaml
  chart/README.md
  chart/templates/_helpers.tpl
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/secret.yaml
  chart/templates/servicemonitor.yaml
  chart/templates/sparrowConfig.yaml
  chart/values.yaml
  cmd/root.go
  go.mod
  go.sum
Labels: bug, docs, housekeeping, area/helm

#76 docs: prepare v0.3.0 release
  README.md
  chart/README.md
  chart/values.yaml
Labels: docs, housekeeping

#87 feat: logging verbosity
  README.md
  cmd/run.go
  internal/logger/logger.go
  internal/logger/logger_test.go
Labels: feature

#90 fix: return error to trigger retry mechanism
  pkg/checks/latency/latency.go
Labels: bug, area/checks

#88 feat: added new workflow to prune old images
  .github/workflows/prune.yml
Labels: feature, housekeeping, good first issue

#94 fix: removed outdated regex
  .github/workflows/prune.yml
Labels: feature, housekeeping, good first issue
