Repository telekom/sparrow, pull requests merged in 2024-02, with the labels that each got.

#93 refactor/typed-runtime-cfg
  .github/workflows/end2end.yml
  README.md
  chart/README.md
  chart/values.yaml
  cmd/run.go
  go.mod
  internal/helper/decode.go
  internal/helper/decode_test.go
  pkg/checks/base.go
  pkg/checks/base_moq.go
  pkg/checks/checks.go
  pkg/checks/dns/dns.go
  pkg/checks/dns/dns_test.go
  pkg/checks/dns/metrics.go
  pkg/checks/dns/metrics_test.go
  pkg/checks/errors.go
  pkg/checks/errors/errors.go
  pkg/checks/health/health.go
  pkg/checks/health/health_test.go
  pkg/checks/latency/latency.go
  pkg/checks/latency/latency_test.go
  pkg/checks/oapi.go
  pkg/checks/register/register.go
  pkg/checks/runtime/runtime.go
  pkg/checks/types/checks.go
  pkg/config/config.go
  pkg/config/file.go
  pkg/config/file_test.go
  pkg/config/http.go
  pkg/config/http_test.go
  pkg/config/loader.go
  pkg/config/runtime_config.go
  pkg/config/testdata/config.yaml
  pkg/config/validate_test.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/factory/factory.go
  pkg/factory/factory_test.go
  pkg/sparrow/api_test.go
  pkg/sparrow/gitlab/gitlab.go
  pkg/sparrow/gitlab/gitlab_test.go
  pkg/sparrow/gitlab/test/mockclient.go
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
  pkg/sparrow/targets/gitlab.go
  pkg/sparrow/targets/gitlab_test.go
  pkg/sparrow/targets/targetmanager.go
  pkg/sparrow/targets/test/mocktargets.go
Labels: refactoring

#96 feat: dynamic file loader
  .github/workflows/end2end.yml
  pkg/config/file.go
  pkg/config/file_test.go
  pkg/config/http.go
  pkg/config/http_test.go
  pkg/config/test/data/config.yaml
  pkg/config/test/filesystem.go
  pkg/config/validate.go
  pkg/config/validate_test.go
  pkg/factory/factory.go
Labels: feature

#95 refactor: cleanup and move API
  README.md
  go.mod
  pkg/api/api.go
  pkg/api/api_moq.go
  pkg/api/api_test.go
  pkg/api/errors.go
  pkg/api/routingtree.go
  pkg/api/routingtree_test.go
  pkg/checks/base.go
  pkg/config/config.go
  pkg/config/file.go
  pkg/factory/factory_test.go
  pkg/sparrow/api.go
  pkg/sparrow/api_test.go
  pkg/sparrow/handlers.go
  pkg/sparrow/handlers_test.go
  pkg/sparrow/metrics.go
  pkg/sparrow/metrics_test.go
  pkg/sparrow/run.go
  pkg/sparrow/run_test.go
  pkg/sparrow/targets/test/mocktargets.go
Labels: refactoring, housekeeping, area/api

#103 feat/registration-update
  pkg/config/config.go
  pkg/sparrow/run_test.go
  pkg/sparrow/targets/errors.go
  pkg/sparrow/targets/gitlab.go
  pkg/sparrow/targets/gitlab_test.go
  pkg/sparrow/targets/targetmanager.go
  pkg/sparrow/targets/targetmanager_test.go
Labels: refactoring, housekeeping, area/target-manager

#104 feat/tm-config-update
  README.md
  chart/values.yaml
  pkg/sparrow/gitlab/test/mockclient.go
  pkg/sparrow/targets/errors.go
  pkg/sparrow/targets/gitlab.go
  pkg/sparrow/targets/gitlab_test.go
  pkg/sparrow/targets/targetmanager.go
  pkg/sparrow/targets/targetmanager_test.go
Labels: area/target-manager

#106 refactor: use one result channel for all checks
  pkg/checks/base.go
  pkg/checks/base_moq.go
  pkg/checks/dns/dns.go
  pkg/checks/dns/dns_test.go
  pkg/checks/health/health.go
  pkg/checks/health/health_test.go
  pkg/checks/latency/latency.go
  pkg/checks/latency/latency_test.go
  pkg/checks/oapi_test.go
  pkg/sparrow/controller.go
  pkg/sparrow/controller_test.go
  pkg/sparrow/handlers_test.go
  pkg/sparrow/run.go
Labels: refactoring

#102 refactor: check reconcilation
  chart/README.md
  cmd/flag.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/checks/base.go
  pkg/checks/base_moq.go
  pkg/checks/dns/dns.go
  pkg/checks/dns/dns_test.go
  pkg/checks/health/health.go
  pkg/checks/health/health_test.go
  pkg/checks/latency/latency.go
  pkg/checks/latency/latency_test.go
  pkg/checks/oapi_test.go
  pkg/checks/runtime/checks.go
  pkg/checks/runtime/config.go
  pkg/config/loader.go
  pkg/config/loader_moq.go
  pkg/sparrow/controller.go
  pkg/sparrow/controller_errors.go
  pkg/sparrow/controller_test.go
  pkg/sparrow/handlers.go
  pkg/sparrow/handlers_test.go
  pkg/sparrow/run.go
  pkg/sparrow/run_errors.go
  pkg/sparrow/run_test.go
Labels: refactoring

#108 feat: disable continuous loading of check config
  README.md
  pkg/config/file.go
  pkg/config/file_test.go
  pkg/config/http.go
  pkg/config/http_test.go
  pkg/config/validate.go
Labels: bug, feature, area/config

#109 fix: missing tags on target manager config field
  pkg/sparrow/targets/targetmanager.go
Labels: bug, area/config

#110 chore: prepare new release
  README.md
  chart/Chart.yaml
  chart/README.md
  chart/values.yaml
Labels: docs, housekeeping

#114 Targetmanager doesn't need timer reset
  pkg/sparrow/targets/gitlab.go
Labels: area/target-manager
